version: "3.8"
services:

#    snmptrapd:
#        build:
#            context: ./dock_snmptrapd
#            dockerfile: Dockerfile
#        networks:
#            - the_network
#        container_name: snmptrapd


    ra:
        build:
            context: ./dock_ra
            dockerfile: Dockerfile
        networks:
            - the_network
        container_name: ra



networks:
    the_network:
        name: the_network
        driver: bridge

