#!/bin/sh
                                                                         $
read host
read ip
vars=
                                                                         $
while read oid val
do
  if [ "$vars" = "" ]
  then
    vars="$oid = $val\n"
  else
    vars="$vars, $oid = $val\n"
  fi
done
                                                                         $

# The Original:
#echo trap: $1 $host $ip $vars > /tmp/go.out  
# Testing
#echo trap: $vars > /tmp/go.out
echo okay
